### ISSUE TITLE
yarn build: ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by eacousineau** [zawys/vscode-as-git-mergetool#11]
## Steps to reproduce

```
$ cd vscode-as-git-mergetool

$ git log -n 1 --oneline --no-decorate
de60bc0 update dependencies

$ python -m venv ./.venv/
$ .venv/bin/pip install nodeenv==1.6.0
$ .venv/bin/nodeenv ./.nodeenv/
 * Install prebuilt node (17.1.0) ..... done.
$ source .nodeenv/bin/activate
$ npm install --global yarn
$ yarn --version
1.22.17
$ minimal^C
$ yarn
$ yarn build
...
$ webpack --mode production
${PWD}/node_modules/loader-runner/lib/LoaderRunner.js:146
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (${PWD}/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.update (${PWD}/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (${PWD}/node_modules/webpack-sources/lib/SourceMapSource.js:233:8)
    at NormalModule._initBuildHash (${PWD}/node_modules/webpack/lib/NormalModule.js:853:17)
    at handleParseResult (${PWD}/node_modules/webpack/lib/NormalModule.js:918:10)
    at ${PWD}/node_modules/webpack/lib/NormalModule.js:1009:4
    at processResult (${PWD}/node_modules/webpack/lib/NormalModule.js:732:11)
    at ${PWD}/node_modules/webpack/lib/NormalModule.js:792:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

(FWIW, Since `node` is not a primary tool for development for me (I use Python), I like to keep `node` and its ecosystem encapsulated. I use PyPI `nodeenv` to do so.)

## Expected behavior

It works?

Workaround as mentioned here: https://github.com/expo/expo-cli/issues/3943#issuecomment-954986343
Use stable version of node; from website, current latest stable is 16.13.0: https://nodejs.org/en/

Changing install line above to read `.venv/bin/nodeenv --node==16.13.0 .nodeenv/` fixes it.

## Environment

- Version of the extension: de60bc0
- Operating system: Ubuntu 20.04
- VS Code version [use Code command “Help: About”]:  N/A
- Other installed extensions (if applicable): N/A

**Comment by Crystal-RainSlide** [comment]
Also see: https://github.com/webpack/webpack/issues/14532
