### ISSUE TITLE
Still not working in WSL

### ISSUE THREAD

**Issue by mvoppen** [zawys/vscode-as-git-mergetool#7]
The previous bug regarding configuring the extension inside WSL is fixed.

But running `git mergetool` fails always with the following error:

```
marko@***---***:~/git-repos/***---***$ git mergetool
Merging:
src/***---***/importers/***---***/***---***.cpp

Normal merge conflict for 'src/***---***/importers/***---***/***---***.cpp':
  {local}: modified file
  {remote}: modified file
/home/marko/git-repos/cryptoservice/src/***---***/importers/***---***/***---***_BASE_3550.cpp:1
#include "libplatform/types.h"
^^^^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
src/***---***/importers/***---***/***---***.cpp seems unchanged.
Was the merge successful [y/n]? n
merge of src/***---***/importers/***---***/***---***.cpp failed

```

**Comment by zawys** [comment]
Hi @mvoppen!

1. As stated in a [previous comment](https://github.com/zawys/vscode-as-git-mergetool/issues/2#issuecomment-702075203), sometimes error messages from unrelated child processes of VS Code are printed into the terminal. I think this is an issue of NodeJS, VSCode or node-pty. `git mergetool` actually terminates normally.

2. Which fixed bug do you mean?

3. From your post I guess that the merge conflict does open in VS Code. Please post the parts of your `.gitconfig` (in your home directory) related to merging.

**Comment by mvoppen** [comment]
> 1. As stated in a [previous comment](https://github.com/zawys/vscode-as-git-mergetool/issues/2#issuecomment-702075203), sometimes error messages from unrelated child processes of VS Code are printed into the terminal. I think this is an issue of NodeJS, VSCode or node-pty. `git mergetool` actually terminates normally.

Yes, `git mergetool` terminates *normally* after the actual action failed. My understanding is that running `git mergetool` should open the merge issue into VSC to be resolved there but that action fails with the output from my initial post.

> 2. Which fixed bug do you mean?

Some weeks ago I issued #6 about not being able to configure the extension. Now I can configure the extension. At least there is something happening now when running `git mergetool` now.

> 3. From your post I guess that the merge conflict does open in VS Code. Please post the parts of your `.gitconfig` (in your home directory) related to merging.

No, that is what I would expect to happen. What I posted initially is *all* what actual is happening. I see only these messages all the time running `git mergetool` and I suppose these messages are *not* unrelated.

```
[mergetool]
        keepTemporaries = false
        keepBackup = false
[mergetool "code"]
        cmd = \"/home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node\" \"$BASE\"
[merge]
        tool = code
        conflictstyle = merge
```

**Comment by zawys** [comment]
Thanks for your detailed answers! That was fun! Let’s repeat it for a while! ;)

Sorry if I’m wrong about how WSL works – I currently don’t have access to Windows.

1. What happens when you run `"/home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node"` in a WSL shell? (Maybe you need to look up the current hexadecimal code.)
2. What is output when you run `/home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node --help` in WSL?
3. What is output when you run `which code` in WSL?
4. Does it fix your issue when you replace `\"/home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node\"` by the output of `which code` in `.gitconfig`?
5. What is the output of `ls /home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/` in WSL?

**Comment by mvoppen** [comment]
> Thanks for your detailed answers! That was fun! Let’s repeat it for a while! ;)
> 
> Sorry if I’m wrong about how WSL works – I currently don’t have access to Windows.
> 
> 1. What happens when you run `"/home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node"` in a WSL shell? (Maybe you need to look up the current hexadecimal code.)

```
$ /home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node
Welcome to Node.js v14.16.0.
Type ".help" for more information.
>
```
seems fine

> 2. What is output when you run `/home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node --help` in WSL?

```$ /home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node --help
Usage: node [options] [ script.js ] [arguments]
       node inspect [options] [ script.js | host:port ] [arguments]
...
```

> 3. What is output when you run `which code` in WSL?

Empty.  `code` is not in $PATH.

> 4. Does it fix your issue when you replace `\"/home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node\"` by the output of `which code` in `.gitconfig`?

`code` is not in the path. The `node` in `.git/config` could be replaced by `bin/code` to get a valid path. Currently I don't have a merge situation. So I get `No files need merging` when I run `git mergetool` now.  Maybe you could give me a hint how to easily create a merge situation?

> 5. What is the output of `ls /home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/` in WSL?

`bin  extensions  LICENSE  node  node_modules  out  package.json  product.json  server.sh`

**Comment by zawys** [comment]
Thanks again! Very insightful.

1. That `code` is not in $PATH in your WSL environment seems to be different from the setup described in the [VS Code documentation regarding WSL](https://code.visualstudio.com/docs/remote/wsl#_opening-a-terminal-in-wsl). There, they are able to run `code .` in WSL to open VS Code, which does not work in your setup, right? Please check that.

2. What are the reasons for the difference? Also note the hint in the documentation:

    > Note: When prompted to Select Additional Tasks during installation, be sure to check the Add to PATH option so you can easily open a folder in WSL using the code command.

3. How do *you* regularly launch VS Code in WSL?

4. By `bin/code`, do you mean `/usr/bin/code` or `/home/marko/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/bin/code`?

5. You can create a merge conflict situation by running following commands in WSL. Replace the `<placeholders>`. But make sure you commit and push your WIP before.

    ```shell
    cd <some repository path>
    git checkout -b merge_test
    echo base > x
    git add x
    git commit -m 'x=base'
    git checkout -b merge_test2
    echo remote > x
    git commit -am 'x=remote'
    git checkout merge_test
    echo local > x
    git commit -am 'x=local'
    git merge merge_test2
    ```

    You can then reset to the previous state via:

    ```shell
    git merge --abort
    git checkout <previous branch name>
    git branch -D merge_test merge_test2
    ```

**Comment by mvoppen** [comment]
So, now I changed the config line to the `.../bin/code` instead of `node` and that improves the things much.

The error message is gone and file `x` in your sample above is now opened in VSC and that looks so far OK.

But the rest of the workflow does still not work in this scenario.  The terminal looks like this:

```
$ git mergetool 
Merging:
x

Normal merge conflict for 'x':
  {local}: modified file
  {remote}: modified file
x seems unchanged.
Was the merge successful [y/n]? n
merge of x failed
```

Even if I insert a `-w` option it does not improve: `.../bin/code" -w \"$BASE\"`. I would expect that `git mergetool` waits until `x`is closed like `-x` is described in `code --help` but that does not seem to happen. Maybe `x` is somehow closed and reopened or something else happens.

By the way is there another way to invoke the extension beside `git mergetool`?

**Comment by zawys** [comment]
Ok, good that it works by changing the path.

To help the problem also fix for other users, it would be interesting how it comes, that no `code` is in $PATH. Can you please explain how you installed VS Code in WSL?

> Even if I insert a -w option it does not improve: .../bin/code" -w \"$BASE\". I would expect that git mergetool waits until xis closed like -x is described in code --help but that does not seem to happen. Maybe x is somehow closed and reopened or something else happens.

Standalone `git mergetool` is not really compatible with Code because `code` sometimes reuses a running Code process and the delegating process then exits. But that is no problem. You can just type `y` at the `git mergetool` command prompt when you have finished merging the opened file.

> By the way is there another way to invoke the extension beside git mergetool?

There is! Just press `shift+alt+m` `m` and **m**agic will happen. ;)

**Comment by zawys** [comment]
I'm closing this as this seems to be resolved for the issue opener.

@mvoppen It would be nice if you responded to my question:

> Can you please explain how you installed VS Code in WSL?

**Comment by mvoppen** [comment]
> I'm closing this as this seems to be resolved for the issue opener.

No, it's not resolved. At least the point that the configuration part of this extension writes `.../node` instead of `.../bin/code` into the git configuration file is an open issue, isn't it?
> 
> @mvoppen It would be nice if you responded to my question:
> 
> > Can you please explain how you installed VS Code in WSL?

The short form of our install:

1. Install WSL 1 in Windows 10 using official Microsoft doc
2. Install Debian from MS Store
3. Install Visual Studio Code
4. Install *Remote - WSL* Extension inside VSC
5. Run VSC; in the lower left corner on the status bar now you have an *Open Remote Window* button.

**Comment by zawys** [comment]
> No, it's not resolved. At least the point that the configuration part of this extension writes .../node instead of .../bin/code into the git configuration file is an open issue, isn't it?

You’re right. However, to fix this, we would need to find out why `code` is not in your WSL `PATH`. This is contradictory to the documentation – maybe it was caused by a bug at the time when you configured your VS Code for WSL. I would refrain from doing some fragile path magic to find the (temporary) path of the VS Code launch script – we need a permanent link.

> The short form of our install: …

Thanks for your info.
